version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
      - image: circleci/mysql:5.7

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Update System, Install Chrome, and Xvfb
          command: |
            sudo apt-get update
            sudo apt-get install -y libatk-bridge2.0-0 libatspi2.0-0 libgbm1 libgtk-3-0 libu2f-udev libvulkan1 libxkbcommon0 xvfb
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb || sudo apt --fix-broken install -y

      - run:
          name: Kill existing Xvfb processes
          command: |
            if [ -f /tmp/.X100-lock ]; then
              echo "Removing Xvfb lock file..."
              sudo rm /tmp/.X100-lock
            fi
            if pgrep Xvfb; then
              echo "Killing existing Xvfb processes..."
              sudo pkill Xvfb
            fi

      - run:
          name: Start Xvfb
          command: Xvfb :100 -screen 0 1280x1024x24
          background: true

      - run:
          name: Set DISPLAY Environment Variable
          command: echo 'export DISPLAY=:100' >> $BASH_ENV

      - run:
          name: Install Python Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - run:
          name: Run Data Scraping Script
          command: python 01_data_scraping.py

      - run:
          name: Run Data Cleaning Script
          command: python 02_data_cleaning.py

      - run:
          name: Run Data Storing Script
          command: python 03_data_storing.py

      - run:
          name: Run README Update Script
          command: python 04_update_README.py

workflows:
  version: 2
  scrape-and-store:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
  schedule:
    triggers:
      - schedule:
          cron: "0 1,7,13,19 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build